name: Build slacktui ✨

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}
        run: |
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/${{ matrix.goos }}_${{ matrix.goarch }}/slacktui${EXT}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: slacktui-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/${{ matrix.goos }}_${{ matrix.goarch }}
